# Generated by Django 5.0.6 on 2024-06-12 14:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuartierUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier_code', models.CharField(max_length=15, null=True)),
                ('surface', models.FloatField(null=True)),
                ('up_code', models.CharField(max_length=254, null=True)),
                ('up_nom_1', models.CharField(max_length=254, null=True)),
                ('up_nom_2', models.CharField(max_length=254, null=True)),
                ('quartier_code_court', models.CharField(max_length=254, null=True)),
                ('quartier_nom', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2154)),
            ],
        ),
    ]
