# Generated by Django 5.0.6 on 2024-06-18 07:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0004_remove_quartierup_categorie_delete_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEquipementAlpage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=254)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipementAlpage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('information_complementaire', models.TextField()),
                ('etat', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=2154)),
                ('type_eqpt_aa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eqpt_aas', to='alpages.typeequipementalpage')),
            ],
        ),
    ]
