# Generated by Django 5.0.6 on 2024-06-18 07:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0005_typeequipementalpage_equipementalpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementalpage',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=2154),
        ),
    ]
