# Generated by Django 5.0.6 on 2024-06-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0006_alter_equipementalpage_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementalpage',
            name='quartier_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eqpt_aas', to='alpages.quartierup'),
        ),
    ]
