# Generated by Django 5.0.6 on 2024-06-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0007_equipementalpage_quartier_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartierup',
            name='categorie',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
