# Generated by Django 5.0.6 on 2024-06-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0008_quartierup_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quartierup',
            name='categorie',
        ),
    ]
