# Generated by Django 5.0.6 on 2024-06-25 07:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0009_remove_quartierup_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartierup',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=2154),
        ),
    ]
