# Generated by Django 5.0.6 on 2024-07-04 07:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0010_alter_quartierup_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logement_code', models.CharField(max_length=10)),
                ('statut', models.CharField()),
                ('acces_final', models.CharField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=2154)),
            ],
        ),
    ]
