# Generated by Django 5.0.6 on 2024-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0011_logement'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='activite_laitiere',
            field=models.CharField(choices=[('salle_de_traite', 'salle de traite'), ('salle_de_transformation', 'salle de transformation'), ('les_deux', 'les deux'), ('aucune', 'aucune')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='etat_batiment',
            field=models.CharField(choices=[('bon', 'bon'), ('moyen', 'moyen'), ('delabre', 'délabré')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='multiusage',
            field=models.CharField(choices=[('uniquement_pastoral', 'uniquement pastoral'), ('abri_randonneurs', 'abri randonneurs'), ('refuge_garde', 'refuge gardé'), ('resto_station_ski', 'resto station ski'), ('poste_de_secours', 'poste de secours'), ('autre', 'autre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='proprietaire',
            field=models.CharField(choices=[('communal', 'communal'), ('domanial', 'domanial'), ('prive', 'privé'), ('afp', 'afp'), ('gp', 'gp'), ('departemental', 'départemental'), ('domaine_skiable', 'domaine skiable'), ('autre_collectivite', 'autre collectivité')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='type_logement',
            field=models.CharField(choices=[('logement_principal', 'logement principal'), ('logement_secondaire', 'logement secondaire'), ('abri_sommaire', 'abri sommaire')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logement',
            name='acces_final',
            field=models.CharField(choices=[('carrossable', 'carrossable'), ('4_4', '4*4'), ('quad', 'quad'), ('pedestre', 'pédestre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='logement',
            name='statut',
            field=models.CharField(choices=[('existant', 'existant'), ('besoin', 'besoin')], max_length=50),
        ),
    ]
