# Generated by Django 5.0.6 on 2024-07-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0013_alter_logement_acces_final_alter_logement_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='accueil_public',
            field=models.CharField(choices=[('aucun_accueil', 'aucun accueil du public'), ('accueil_ss_vente', 'accueil du public sans vente'), ('accueil_vente', 'accueil et vente au public'), ('vente_ss_accueil', 'vente sans accueil du public')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='alim_eau',
            field=models.CharField(choices=[('interieur', 'intérieur'), ('ext_inf50', 'extérieur < 50m'), ('ext_sup50', 'extérieur > 50 m'), ('absence', 'absence')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='alim_elec',
            field=models.CharField(choices=[('mini_renouv', 'mini renouvelable'), ('renouv_inter', 'renouvelable intermédiaire'), ('gros_renouv', 'gros renouvelable'), ('reseau_public', 'réseau public'), ('groupe_elec', 'groupe électrogène'), ('absence', 'absence')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='assainissement',
            field=models.CharField(choices=[('puits_perdu', 'puits perdu'), ('fosse_septique', 'fosse septique'), ('tout_egout', "tout à l'égoût"), ('bassin_trt', 'bassin de traitement'), ('champ_epandage', "champ d'épandage"), ('absence', 'absence')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='chauffage',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='chauffe_eau',
            field=models.CharField(choices=[('chauffe_eau_gaz', 'chauffe-eau gaz'), ('chauffe_eau_elec', 'chauffe-eau électrique'), ('poele_bois', 'poêle bouilleur au bois'), ('chauffe_eau_solaire', 'chauffe-eau solaire'), ('absence', 'absence')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='dispo_eau',
            field=models.CharField(choices=[('a_volonte', 'à volonté'), ('irregulier', 'irrégulier'), ('absence', 'absence'), ('inconnnu', 'inconnu')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='mixite_possible',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('inconnu', 'inconnu')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='origine_eau',
            field=models.CharField(choices=[('source_captee', 'source captée'), ('eau_de_surface', 'eau de surface'), ('impluvium', 'impluvium'), ('recup_toiture', 'récupération toiture'), ('reseau', 'réseau'), ('transport', 'transport'), ('absence', 'absence')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='presence_douche',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('inconnu', 'inconnu')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='qualite_eau',
            field=models.CharField(choices=[('non_consommee', 'non consommée'), ('eau_consommee', 'eau consommée'), ('eau_traitee', 'eau traitée'), ('eau_regl_potable', 'eau réglementairement potable')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='stockage_indep',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='surface_logement',
            field=models.CharField(choices=[('inf14', '< 14 m2'), ('sup14_inf20', '[14 - 20] m2'), ('sup20_inf40', ']20 - 40] m2'), ('sup40_inf80', ']40 - 80] m2'), ('sup80', '> 80 m2')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='type_wc',
            field=models.CharField(choices=[('toilettes_seches', 'toilettes sèches'), ('classique', 'classique'), ('absence', 'absence'), ('inconnu', 'inconnu')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logement',
            name='activite_laitiere',
            field=models.CharField(choices=[('salle_de_traite', 'salle de traite'), ('salle_de_transformation', 'salle de transformation'), ('les_deux', 'les deux'), ('aucune', 'aucune'), ('inconnu', 'inconnu')], max_length=50, null=True),
        ),
    ]
