# Generated by Django 5.0.6 on 2024-07-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0014_logement_accueil_public_logement_alim_eau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='assainissement',
            field=models.CharField(choices=[('puits_perdu', 'puits perdu'), ('fosse_septique', 'fosse septique'), ("tout à l'égoût", "tout à l'égoût"), ('bassin_trt', 'bassin de traitement'), ('champ_epandage', "champ d'épandage"), ('absence', 'absence')], max_length=50, null=True),
        ),
    ]
