# Generated by Django 5.0.6 on 2024-07-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0016_alter_logement_acces_final_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logement',
            old_name='proprietaire',
            new_name='propriete',
        ),
    ]
