# Generated by Django 5.0.6 on 2024-07-23 13:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0017_rename_proprietaire_logement_propriete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartieralpage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=2154)),
                ('quartier_code_court', models.CharField(blank=True, max_length=10, null=True)),
                ('date_presence_troupeau', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'alpages_quartieralpage',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='logement',
            name='propriete',
            field=models.CharField(blank=True, choices=[('communal', 'communal'), ('domanial', 'domanial'), ('prive', 'privé'), ('afp', 'afp'), ('gp', 'gp'), ('departemental', 'départemental'), ('domaine_skiable', 'domaine skiable'), ('autre collectivité', 'autre collectivité')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quartierup',
            name='quartier_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quartierup',
            name='quartier_code_court',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='quartierup',
            name='quartier_nom',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='quartierup',
            name='surface',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartierup',
            name='up_code',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='quartierup',
            name='up_nom_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='quartierup',
            name='up_nom_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
