# Generated by Django 5.0.6 on 2024-08-06 08:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0019_alter_typeequipementalpage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementalpage',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=2154),
        ),
    ]
