# Generated by Django 5.0.6 on 2024-08-08 06:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0022_typeequipementalpage_typegeom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementalpage',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=2154),
        ),
    ]
