# Generated by Django 5.0.6 on 2024-10-03 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0026_unitepastorale_proprietaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDeSuivi',
            fields=[
                ('id_type_suivi', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDeSuivi',
            fields=[
                ('id_plan_suivi', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('type_suivi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_de_suivi', to='alpages.typedesuivi')),
            ],
        ),
    ]
