# Generated by Django 5.0.6 on 2024-10-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0027_typedesuivi_plandesuivi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConvention',
            fields=[
                ('id_type_convention', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
