# Generated by Django 5.0.6 on 2024-10-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0029_conventiondexploitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDeMesure',
            fields=[
                ('id_type_mesure', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MesureDePlan',
            fields=[
                ('id_mesure_plan', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('commentaire', models.CharField(blank=True, max_length=50, null=True)),
                ('debut_periode', models.DateField(blank=True, null=True)),
                ('fin_periode', models.DateField(blank=True, null=True)),
                ('plan_suivi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures_de_plan', to='alpages.plandesuivi')),
                ('type_mesure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures_de_plan', to='alpages.typedemesure')),
            ],
        ),
    ]
