# Generated by Django 5.0.6 on 2024-10-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0030_typedemesure_mesuredeplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandesuivi',
            name='unite_pastorale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_de_suivi', to='alpages.unitepastorale'),
        ),
    ]
