# Generated by Django 5.0.6 on 2024-10-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0031_plandesuivi_unite_pastorale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleveur',
            fields=[
                ('id_eleveur', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_eleveur', models.CharField(max_length=50)),
                ('prenom_eleveur', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_eleveur', models.CharField(blank=True, max_length=50, null=True)),
                ('mail_eleveur', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse_eleveur', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
