# Generated by Django 5.0.6 on 2024-10-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0034_rename_eleveur_exploitant_president'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtreCompose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpages.eleveur')),
                ('exploitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpages.exploitant')),
            ],
            options={
                'unique_together': {('exploitant', 'eleveur')},
            },
        ),
    ]
