# Generated by Django 5.0.6 on 2024-10-15 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0037_abridurgence'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficierDe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('abri_urgence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaires', to='alpages.abridurgence')),
                ('exploitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaires', to='alpages.exploitant')),
            ],
            options={
                'unique_together': {('exploitant', 'abri_urgence')},
            },
        ),
    ]
