# Generated by Django 5.0.6 on 2024-10-16 07:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0038_beneficierde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berger',
            fields=[
                ('id_berger', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_berger', models.CharField(max_length=50)),
                ('prenom_berger', models.CharField(max_length=50)),
                ('tel_berger', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse_berger', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruche',
            fields=[
                ('id_ruche', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=2154)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCheptel',
            fields=[
                ('id_type_cheptel', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('espece', models.CharField(max_length=50)),
                ('race', models.CharField(blank=True, max_length=50, null=True)),
                ('production', models.CharField(blank=True, max_length=50, null=True)),
                ('stade_maturite', models.CharField(blank=True, max_length=50, null=True)),
                ('pension', models.BooleanField()),
            ],
        ),
    ]
