# Generated by Django 5.0.6 on 2024-10-16 09:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0039_berger_ruche_typecheptel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEvenement',
            fields=[
                ('id_type_evenement', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id_evenement', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_evenement', models.DateField()),
                ('observateur', models.CharField(max_length=50)),
                ('date_observation', models.DateField()),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=2154)),
                ('mesure_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='alpages.mesuredeplan')),
                ('unite_pastorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='alpages.unitepastorale')),
                ('type_evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='alpages.typeevenement')),
            ],
        ),
    ]
