# Generated by Django 5.0.6 on 2024-10-28 08:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0044_conventiondexploitation_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficierde',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=2154),
        ),
    ]
