# Generated by Django 5.0.6 on 2024-10-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0045_beneficierde_geometry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beneficierde',
            unique_together=set(),
        ),
    ]
