# Generated by Django 5.0.6 on 2024-10-29 11:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0047_remove_beneficierde_id_beneficierde_id_beneficier_de'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogementTest',
            fields=[
                ('id_logement_test', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_logement_test', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=2154)),
            ],
        ),
    ]
