# Generated by Django 5.0.6 on 2024-10-29 13:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0049_rename_geom_logementtest_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuartierPasto',
            fields=[
                ('id_quartier', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code_quartier', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_quartier', models.CharField(blank=True, max_length=50, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=2154)),
                ('unite_pastorale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quartiers', to='alpages.unitepastorale')),
            ],
        ),
    ]
