# Generated by Django 5.0.6 on 2024-10-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0050_quartierpasto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipementAlpage',
        ),
        migrations.DeleteModel(
            name='TypeEquipementAlpage',
        ),
    ]
