# Generated by Django 5.0.6 on 2024-11-06 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0054_ruche_situation_exploitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardeSituation',
            fields=[
                ('id_garde_situation', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=500, null=True)),
                ('berger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardes_situation', to='alpages.berger')),
                ('situation_exploitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardes_situation', to='alpages.situationdexploitation')),
            ],
        ),
    ]
