# Generated by Django 5.0.6 on 2024-11-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0058_rename_situation_exploiter_situation_exploitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='abridurgence',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='abridurgence',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abridurgence',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='abridurgence',
            name='modified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
