# Generated by Django 5.0.6 on 2024-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0059_abridurgence_created_by_abridurgence_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodite',
            fields=[
                ('id_commodite', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
