# Generated by Django 5.0.6 on 2024-11-12 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0060_commodite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodite',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='LogementCommodite',
            fields=[
                ('id_logement_commodite', models.BigIntegerField(primary_key=True, serialize=False)),
                ('etat', models.CharField(max_length=50)),
                ('commentaire', models.CharField(blank=True, max_length=50, null=True)),
                ('quantite', models.CharField(blank=True, max_length=50, null=True)),
                ('commodite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logements', to='alpages.commodite')),
                ('logement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commodites', to='alpages.logement')),
            ],
        ),
    ]
