# Generated by Django 5.0.6 on 2024-11-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0061_alter_commodite_description_logementcommodite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecheptel',
            name='pension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
