# Generated by Django 5.0.6 on 2024-11-13 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0062_alter_typecheptel_pension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitepastorale',
            name='proprietaire',
        ),
        migrations.CreateModel(
            name='UPProprietaire',
            fields=[
                ('id_up_proprietaire', models.BigIntegerField(primary_key=True, serialize=False)),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_pastorales', to='alpages.proprietairefoncier')),
                ('unite_pastorale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietaires', to='alpages.unitepastorale')),
            ],
        ),
    ]
