# Generated by Django 5.0.6 on 2025-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0066_remove_exploitant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='nom_logement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
