# Generated by Django 5.0.6 on 2025-10-28 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0067_logement_nom_logement'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='unite_pastorale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logements', to='alpages.unitepastorale'),
        ),
    ]
