# Generated by Django 5.0.6 on 2025-12-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0069_typeequipement_equipementexploitant_equipementalpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typecheptel',
            name='pension',
        ),
        migrations.AddField(
            model_name='elever',
            name='pension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
