# Generated by Django 5.0.6 on 2025-12-03 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0070_remove_typecheptel_pension_elever_pension'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbriDUrgenceCommodite',
            fields=[
                ('id_abri_urgence_commodite', models.BigIntegerField(primary_key=True, serialize=False)),
                ('etat', models.CharField(max_length=50)),
                ('commentaire', models.CharField(blank=True, max_length=50, null=True)),
                ('quantite', models.CharField(blank=True, max_length=50, null=True)),
                ('abri_urgence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commodites', to='alpages.abridurgence')),
                ('commodite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abris_urgence', to='alpages.commodite')),
            ],
        ),
    ]
