# Generated by Django 5.0.6 on 2025-12-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0071_abridurgencecommodite'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitepastorale',
            name='secteur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
