# Generated by Django 5.0.6 on 2026-02-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0073_rename_elever_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_pension',
            fields=[
                ('id_categorie_pension', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id_espece', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id_production', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie_animaux',
            fields=[
                ('id_categorie_animaux', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('espece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_animaux', to='alpages.espece')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id_race', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('espece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='alpages.espece')),
            ],
        ),
        migrations.CreateModel(
            name='Type_cheptel',
            fields=[
                ('id_type_cheptel', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('categorie_animaux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_cheptel', to='alpages.categorie_animaux')),
                ('pension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_cheptel', to='alpages.categorie_pension')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_cheptel', to='alpages.production')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_cheptel', to='alpages.race')),
            ],
        ),
        migrations.CreateModel(
            name='Cheptel',
            fields=[
                ('id_cheptel', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('nombre_animaux', models.IntegerField()),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('eleveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheptels', to='alpages.eleveur')),
                ('situation_exploitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheptels', to='alpages.situationdexploitation')),
                ('type_cheptel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheptels', to='alpages.type_cheptel')),
            ],
        ),
    ]
