# Generated by Django 5.0.6 on 2026-03-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0075_alter_exploitant_id_exploitant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleveur',
            name='id_eleveur',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
