# Generated by Django 5.0.6 on 2026-03-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0076_alter_eleveur_id_eleveur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie_animaux',
            name='id_categorie_animaux',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorie_pension',
            name='id_categorie_pension',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='espece',
            name='id_espece',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='production',
            name='id_production',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='race',
            name='id_race',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typecheptel',
            name='id_type_cheptel',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeconvention',
            name='id_type_convention',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedemesure',
            name='id_type_mesure',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedesuivi',
            name='id_type_suivi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedexploitant',
            name='id_type_exploitant',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeequipement',
            name='id_type_equipement',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeevenement',
            name='id_type_evenement',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
