# Generated by Django 5.0.6 on 2026-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0077_alter_categorie_animaux_id_categorie_animaux_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_cheptel',
            name='id_type_cheptel',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
