# Generated by Django 5.0.6 on 2026-03-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0078_alter_type_cheptel_id_type_cheptel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elever',
        ),
    ]
