# Generated by Django 5.0.6 on 2026-03-31 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpages', '0079_delete_elever'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProprietaireUnitePastorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_pastorales_proprietaire', to='alpages.proprietairefoncier')),
                ('unite_pastorale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietaires_unite_pastorale', to='alpages.unitepastorale')),
            ],
        ),
        migrations.DeleteModel(
            name='UPProprietaire',
        ),
    ]
